server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_9ea6d9cb1442
    token: weixin
    app-id: wx90813c7b140f7d13
    app-secret: eac1ecb9ccaa5d63342beadd7cf3c32b
    template_id: 9djrX1iJ6lrBUATIAN1NKgsIy7Y8-rRaLbZN5P2zLbw


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.10.88:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat





  # Redis
#  redis:
#    sdk:
#      config:
#        host: 192.168.10.88
#        port: 6399
#        password: 123456
#        pool-size: 10
#        min-idle-size: 5
#        idle-timeout: 30000
#        connect-timeout: 5000
#        retry-attempts: 3
#        retry-interval: 1000
#        ping-interval: 60000
#        keep-alive: true




# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml